version: "3.9"
services:
  proyectito:
    container_name: proyectito
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    links:
      - datitos
    volumes:
      - .:/usr/src/app
  datitos:
    container_name: datitos
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
