version: "3.9"
services:
  proyectito:
    depends_on:
      - datitos
    container_name: proyectito
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # volumes:
    #  - ../:/usr/src/app
  datitos:
    container_name: datitos
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
